/// Lookup tables

create table public.cities (
  city_id serial not null,
  city_name text null,
  constraint cities_pkey primary key (city_id),
  constraint cities_city_name_key unique (city_name)
) TABLESPACE pg_default;



create table public.venues (
  venue_id serial not null,
  venue_name text null,
  city_id integer null,
  constraint venues_pkey primary key (venue_id),
  constraint venues_venue_name_key unique (venue_name),
  constraint venues_city_id_fkey foreign KEY (city_id) references cities (city_id)
) TABLESPACE pg_default;



create table public.umpires (
  umpire_id serial not null,
  umpire_name text null,
  constraint umpires_pkey primary key (umpire_id),
  constraint umpires_umpire_name_key unique (umpire_name)
) TABLESPACE pg_default;



create table public.teams (
  team_id serial not null,
  team_name text null,
  constraint teams_pkey primary key (team_id),
  constraint teams_team_name_key unique (team_name)
) TABLESPACE pg_default;


create table public.seasons (
  season_id serial not null,
  season_year integer null,
  constraint seasons_pkey primary key (season_id),
  constraint seasons_season_year_key unique (season_year)
) TABLESPACE pg_default;



create table public.players (
  player_id serial not null,
  player_name text null,
  constraint players_pkey primary key (player_id),
  constraint players_player_name_key unique (player_name)
) TABLESPACE pg_default;




/// FACTS TABLES DELIVERIES AND MATCHES 


create table public.deliveries (
  match_id bigint not null,
  inning smallint not null,
  over smallint not null,
  ball smallint not null,
  batting_team_id integer null,
  bowling_team_id integer null,
  batter_id integer null,
  bowler_id integer null,
  non_striker_id integer null,
  batsman_runs smallint null,
  extra_runs smallint null,
  total_runs smallint null,
  extras_type public.extras_type_enum null,
  is_wicket boolean null,
  player_dismissed_id integer null,
  dismissal_kind public.dismissal_enum null,
  fielder_id integer null,
  delivery_id bigint generated by default as identity not null,
  constraint deliveries_pkey primary key (delivery_id),
  constraint deliveries_match_ball_key unique (match_id, inning, over, ball),
  constraint deliveries_delivery_id_key unique (delivery_id),
  constraint deliveries_bowling_team_id_fkey foreign KEY (bowling_team_id) references teams (team_id),
  constraint deliveries_fielder_id_fkey foreign KEY (fielder_id) references players (player_id),
  constraint deliveries_match_id_fkey foreign KEY (match_id) references matches (match_id) on delete CASCADE,
  constraint deliveries_non_striker_id_fkey foreign KEY (non_striker_id) references players (player_id),
  constraint deliveries_batter_id_fkey foreign KEY (batter_id) references players (player_id),
  constraint deliveries_player_dismissed_id_fkey foreign KEY (player_dismissed_id) references players (player_id),
  constraint deliveries_batting_team_id_fkey foreign KEY (batting_team_id) references teams (team_id),
  constraint deliveries_bowler_id_fkey foreign KEY (bowler_id) references players (player_id)
) TABLESPACE pg_default;

create index IF not exists deliveries_batter_id_idx on public.deliveries using btree (batter_id) TABLESPACE pg_default;

create index IF not exists deliveries_bowler_id_idx on public.deliveries using btree (bowler_id) TABLESPACE pg_default;




create table public.matches (
  match_id bigint not null,
  season_id integer null,
  city_id integer null,
  venue_id integer null,
  match_date date null,
  match_type text null,
  team1_id integer null,
  team2_id integer null,
  toss_winner_id integer null,
  toss_decision public.toss_decision_type null,
  winner_id integer null,
  result public.result_type null,
  result_margin integer null,
  target_runs integer null,
  target_overs real null,
  super_over boolean null,
  method text null,
  umpire1_id integer null,
  umpire2_id integer null,
  player_of_match integer null,
  constraint matches_pkey primary key (match_id),
  constraint matches_player_of_match_fkey foreign KEY (player_of_match) references players (player_id),
  constraint matches_season_id_fkey foreign KEY (season_id) references seasons (season_id),
  constraint matches_team1_id_fkey foreign KEY (team1_id) references teams (team_id),
  constraint matches_team2_id_fkey foreign KEY (team2_id) references teams (team_id),
  constraint matches_toss_winner_id_fkey foreign KEY (toss_winner_id) references teams (team_id),
  constraint matches_umpire1_id_fkey foreign KEY (umpire1_id) references umpires (umpire_id),
  constraint matches_umpire2_id_fkey foreign KEY (umpire2_id) references umpires (umpire_id),
  constraint matches_venue_id_fkey foreign KEY (venue_id) references venues (venue_id),
  constraint matches_city_id_fkey foreign KEY (city_id) references cities (city_id),
  constraint matches_winner_id_fkey foreign KEY (winner_id) references teams (team_id)
) TABLESPACE pg_default;

create index IF not exists matches_winner_id_season_id_idx on public.matches using btree (winner_id, season_id) TABLESPACE pg_default;